In [9]:
import numpy as np
y_true = np.array([[2,0,0],[2,1],[0,0,0,0]]) # 1-D array with shape of (num_samples,)
y_true.shape

(3,)

In [10]:
y_true

array([list([2, 0, 0]), list([2, 1]), list([0, 0, 0, 0])], dtype=object)

In [11]:
y_true = np.array([s for s in y_true if sum(s)!=0])
y_true

array([list([2, 0, 0]), list([2, 1])], dtype=object)

In [12]:
y_pred = np.array([[2,0,0],[2,0],[0,0,0,0]]) # 1-D array with shape of (num_samples,)
y_pred.shape

(3,)

In [28]:
y_true = np.array([2,0,0,2,1,0,0,0,0])
y_true.shape

(9,)

In [29]:
y_pred = np.array([2,0,0,2,0,0,0,0,0])
y_pred.shape

(9,)

In [33]:
item_id = np.array([
 [5],
 [5],
 [5],
 [6],
 [6],
 [4],
 [4],
 [4],
 [4],
])
item_id = item_id.reshape(len(item_id)) # is item_id ordered?
item_id.shape

(9,)

In [31]:
from collections import Counter, OrderedDict

class OrderedCounter(Counter, OrderedDict):
    'Counter that remembers the order elements are first encountered'

    def __repr__(self):
        return '%s(%r)' % (self.__class__.__name__, OrderedDict(self))

    def __reduce__(self):
        return self.__class__, (OrderedDict(self),)

words = ["oranges", "apples", "apples", "bananas", "kiwis", "kiwis", "apples"]
c = OrderedCounter(words)
#print(c)


id_lengh_dict = OrderedCounter(list(item_id)) # need Counter is ordered key
id_lengh_dict

OrderedCounter(OrderedDict([(5, 3), (6, 2), (4, 4)]))

In [54]:
#---------------------
# initialization
#---------------------
ix = 0
correct_preds, total_correct, total_preds = 0., 0., 0.

for item_id, item_length in id_lengh_dict.items():
    y_t_sentence = list(y_true[ix: ix + item_length])
    y_p_sentence = list(y_pred[ix: ix + item_length])
    print ('item_id',k, v)
    print ('y_t',y_t_sentence)
    print ('y_p',y_p_sentence)
    print (all(v == 0 for v in y_t_sentence))
    #----------
    # core
    #----------
    if all(v == 0 for v in y_t_sentence):
        pass
    else:
        # there is exiting atual y_true
        total_correct += 1
        if np.array_equal(y_t_sentence, y_p_sentence):
            print(type(y_t_sentence))
            # givne the case that we have actual y_ture and y_ture == y_pred
            correct_preds += 1
    if all(v == 0 for v in y_p_sentence):
        pass
    else:
        total_preds += 1
    ix += item_length
#----------
# output
#----------
p   = correct_preds / total_preds if correct_preds > 0 else 0
r   = correct_preds / total_correct if correct_preds > 0 else 0
f1  = 2 * p * r / (p + r) if correct_preds > 0 else 0
# 


item_id 4 4
y_t [2, 0, 0]
y_p [2, 0, 0]
False
<class 'list'>
item_id 4 4
y_t [2, 1]
y_p [2, 0]
False
item_id 4 4
y_t [0, 0, 0, 0]
y_p [0, 0, 0, 0]
True


In [50]:
9.6 / 0.7781100273132324

12.337586797523002

In [51]:
correct_preds, total_correct, total_preds

(1.0, 2.0, 2.0)

In [52]:
p,r,f1

(0.5, 0.5, 0.5)

In [24]:
y_true = np.array([s for s in y_true if sum(s)!=0])
y_pred = np.array([s for s in y_pred if sum(s)!=0])

correct_preds = y_pred==y_true
correct_preds = correct_preds.astype(np.int).sum()
correct_preds

1

In [25]:
correct_preds

1

In [26]:
total_correct = np.array([1 if s.count(0)!= len(s) else 0 for s in y_true]).sum()
total_correct

2

In [27]:
total_preds = np.array([1 if s.count(0) != len(s) else 0 for s in y_pred]).sum()
total_preds

2

In [28]:
for s in y_pred:
    print (s)
    print (s.count(0) == len(s))

[2, 0, 0]
False
[2, 0]
False


In [78]:
len(item_id)

7

In [215]:
tuple_id_index_counts = np.unique(item_id, axis=0, return_counts = True, return_index = True)

In [192]:
tuple_id_index_counts

(array([4, 5, 6, 7]), array([ 7,  0,  4, 12]), array([5, 4, 3, 1]))

In [191]:
for item_id, index, counts in zip(tuple_id_index_counts[0],tuple_id_index_counts[1],tuple_id_index_counts[2]):
    print (item_id)

4
5
6
7


In [216]:
from collections import Counter, OrderedDict

class OrderedCounter(Counter, OrderedDict):
    'Counter that remembers the order elements are first encountered'

    def __repr__(self):
        return '%s(%r)' % (self.__class__.__name__, OrderedDict(self))

    def __reduce__(self):
        return self.__class__, (OrderedDict(self),)

words = ["oranges", "apples", "apples", "bananas", "kiwis", "kiwis", "apples"]
c = OrderedCounter(words)
#print(c)


id_lengh_dict = OrderedCounter(list(item_id)) # need Counter is ordered key
id_lengh_dict

OrderedCounter(OrderedDict([(5, 4), (6, 3)]))

In [207]:
for k, v in id_lengh_dict.items():
    print ('id',k)
    print ('value',v)

id 5
value 4
id 6
value 3
id 4
value 5
id 7
value 1


In [81]:
np.unique(item_id, axis=0)

array([[5],
       [6]])

In [230]:
y_true = np.array([2,0,0,0,0,2,0])
y_true.shape

(7,)

In [231]:
y_true

array([2, 0, 0, 0, 0, 2, 0])

In [235]:
y_pred = np.array([2,1,0,0,0,2,0])


In [236]:
ix = 0
y_true_ = []
y_pred_ = []
for k, v in id_lengh_dict.items():
    print ('idx', idx)
    print ('k',k)
    print (y_true[ix: ix +v])
    y_true_.append(list(y_true[ix: ix +v]))
    y_pred_.append(list(y_pred[ix: ix +v]))
    ix = v
y_true_ = np.array(y_true_)
y_pred_ = np.array(y_pred_)

y_true_

idx 3
k 5
[2 0 0 0]
idx 3
k 6
[0 2 0]


array([list([2, 0, 0, 0]), list([0, 2, 0])], dtype=object)

In [237]:
total_correct = np.array([1 if s.count(0)!= len(s) else 0 for s in y_true_]).sum()
total_preds = np.array([1 if s.count(0) != len(s) else 0 for s in y_pred_]).sum()
correct_preds = y_pred_ == y_true_
correct_preds = correct_preds.astype(np.int).sum()
print ('total_correct',total_correct)
print ('total_preds',total_preds)
print ('correct_preds',correct_preds)
if total_preds != 0:
    p = correct_preds / total_preds
else:
    p = 0
if total_correct != 0:
    r = correct_preds / total_correct
else:
    r = 0
if (p != 0) or (r != 0):
    f1 = 2 * p * r / (p + r)
else:
    f1 = 0
print ('f1', f1)
print ('p', p)
print ('r', r)


total_correct 2
total_preds 2
correct_preds 1
f1 0.5
p 0.5
r 0.5


In [220]:
total_correct

2

In [221]:
total_preds

1

In [222]:
correct_preds

0

In [55]:
lambda a, b, c : a + b + c

<function __main__.<lambda>(a, b, c)>

In [59]:
# closure
def myfunc(x, y, index=None):
    print (x)
    print (y)
    print (index)

def genfunc(index):
    def outputfunc(x, y):
        myfunc(x, y, index)
    return outputfunc


# for i in range(10):
#     printla = genfunc(i)
#     printla("one", "two")

In [61]:
genfunc(1)

<function __main__.genfunc.<locals>.outputfunc(x, y)>